# Generated by Django 3.2.8 on 2022-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220219_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='gif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
