# Generated by Django 3.2.8 on 2022-02-20 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220219_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-create']},
        ),
        migrations.AddField(
            model_name='plan',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
